In [1]:
import pandas as pd

# Replace 'your_file.csv' with the path to your CSV file
file_path = 'clean_data/cleanEvents_1314.csv'

# Load the CSV file into a DataFrame
df = pd.read_csv(file_path)

In [14]:
df['eventOwnerTeam'] = df.apply(lambda row: row['awayTeam'] if row['eventOwnerTeamId'] == row['awayID'] 
                                else row['homeTeam'] if row['eventOwnerTeamId'] == row['homeID'] 
                                else None, axis=1)
df['eventOppTeam'] = df.apply(lambda row: row['awayTeam'] if row['eventOwnerTeamId'] == row['homeID']
                             else row['homeTeam'] if row['eventOwnerTeamId'] == row['awayID']
                             else None, axis=1)

In [13]:
# Calculate the number of unique gameIDs for each team
unique_games = df.groupby('eventOwnerTeam')['gameID'].nunique().reset_index()
unique_games = unique_games.rename(columns={'gameID': 'unique_game_count'})

# Calculate counts for each team and merge with unique game count
stats = df.groupby('eventOwnerTeam').agg(
    CF_count=('shotOutcome', lambda x: x.notna().sum()),
    goal_count=('isGoal', lambda x: (x == 1).sum()),
    takeaway_count=('typeDescKey', lambda x: (x == 'takeaway').sum()), 
    giveaway_count=('typeDescKey', lambda x: (x == 'giveaway').sum()),
    SOG_count=('typeDescKey', lambda x: ((x == 'shot-on-goal') | (x == 'goal')).sum()),
    hit_count=('typeDescKey', lambda x: (x == 'hit').sum())    
).reset_index()

# Merge counts with unique game count
stats = stats.merge(unique_games, on='eventOwnerTeam')

# Divide each count by the unique game count
stats['CF_pg'] = stats['CF_count'] / stats['unique_game_count']
stats['goal_pg'] = stats['goal_count'] / stats['unique_game_count']
stats['takeaway_pg'] = stats['takeaway_count'] / stats['unique_game_count']
stats['giveaway_pg'] = stats['giveaway_count'] / stats['unique_game_count']
stats['SOG_pg'] = stats['SOG_count'] / stats['unique_game_count']
stats['hits_pg'] = stats['hit_count'] / stats['unique_game_count']

stats.head()

,eventOwnerTeam,CF_count,goal_count,takeaway_count,giveaway_count,SOG_count,hit_count,unique_game_count,CF_pg,goal_pg,takeaway_pg,giveaway_pg,SOG_pg,hits_pg
0,ANA,5466,310,520,802,2949,2515,95,57.536842,3.263158,5.473684,8.442105,31.042105,26.473684
1,BOS,5615,295,614,715,3038,2441,94,59.734043,3.138298,6.531915,7.606383,32.319149,25.968085
2,BUF,3975,166,455,542,2199,1992,82,48.475610,2.024390,5.548780,6.609756,26.817073,24.292683
3,CAR,4945,209,785,734,2574,1807,82,60.304878,2.548780,9.573171,8.951220,31.390244,22.036585
4,CBJ,4822,253,522,476,2646,2915,88,54.795455,2.875000,5.931818,5.409091,30.068182,33.125000

In [19]:
# Calculate counts for each condition and merge with unique game count
stats_opp = df.groupby('eventOwnerTeam').agg(
    CA_count=('shotOutcome', lambda x: x.notna().sum()),
    goal_opp_count=('isGoal', lambda x: (x == 1).sum()),
    takeaway_opp_count=('typeDescKey', lambda x: (x == 'takeaway').sum()), 
    giveaway_opp_count=('typeDescKey', lambda x: (x == 'giveaway').sum()),
    SOG_opp_count=('typeDescKey', lambda x: ((x == 'shot-on-goal') | (x == 'goal')).sum()),
    hit_opp_count=('typeDescKey', lambda x: (x == 'hit').sum())    
).reset_index()

# Merge counts with unique game count
stats_opp = stats_opp.merge(unique_games, on='eventOwnerTeam')

# Divide each count by the unique game count
stats_opp['CA_pg'] = stats_opp['CA_count'] / stats_opp['unique_game_count']
stats_opp['goal_opp_pg'] = stats_opp['goal_opp_count'] / stats_opp['unique_game_count']
stats_opp['takeaway_opp_pg'] = stats_opp['takeaway_opp_count'] / stats_opp['unique_game_count']
stats_opp['giveaway_opp_pg'] = stats_opp['giveaway_opp_count'] / stats_opp['unique_game_count']
stats_opp['SOG_opp_pg'] = stats_opp['SOG_opp_count'] / stats_opp['unique_game_count']
stats_opp['hits_opp_pg'] = stats_opp['hit_opp_count'] / stats_opp['unique_game_count']

stats_opp.head()

,eventOwnerTeam,CA_count,goal_opp_count,takeaway_opp_count,giveaway_opp_count,SOG_opp_count,hit_opp_count,unique_game_count,CA_pg,goal_opp_pg,takeaway_opp_pg,giveaway_opp_pg,SOG_opp_pg,hits_opp_pg
0,ANA,5466,310,520,802,2949,2515,95,57.536842,3.263158,5.473684,8.442105,31.042105,26.473684
1,BOS,5615,295,614,715,3038,2441,94,59.734043,3.138298,6.531915,7.606383,32.319149,25.968085
2,BUF,3975,166,455,542,2199,1992,82,48.475610,2.024390,5.548780,6.609756,26.817073,24.292683
3,CAR,4945,209,785,734,2574,1807,82,60.304878,2.548780,9.573171,8.951220,31.390244,22.036585
4,CBJ,4822,253,522,476,2646,2915,88,54.795455,2.875000,5.931818,5.409091,30.068182,33.125000